### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by jjangga0214** [zpm-zsh/zpm#11]
Doesn't this project version yet?

**Comment by horosgrisa** [comment]
@jjangga0214 What do you mean? I think that versioning isn't needed.

**Comment by changwuf31** [comment]
It's needed, gotta rollback to commit on Nov 12 to get it working again

**Comment by horosgrisa** [comment]
@changwuf31  Maybe, will you create an issue? What problem do you have?

**Comment by jjangga0214** [comment]
@horosgrisa Hi!
Why do you think versioning is not needed?

**Comment by horosgrisa** [comment]
@jjangga0214 I don't have time for multiple versions.

**Comment by jjangga0214** [comment]
@horosgrisa 

Then I think you still can do versioning while not maintaining multiple versions, like LTS.
Let you just make version tags, and people specify it.
In this example below, the tag v1.2.3 is used.

```bash
if [[ ! -f ~/.zpm/zpm.zsh ]]; then
  git clone --recursive -b v1.2.3 https://github.com/zpm-zsh/zpm ~/.zpm
fi
```

Without versioning, people will lose reproducibility on their dotfiles. For example, let's say you make a breaking change like only allowing `zpm loads`, not `zpm load`. People's configuration will be broken, once they install zpm on new machine.

To prevent this, you can provide versions, or you have to maintain both `znpm loads` and `znpm load` (theoretically forever). 

Semantic versioning would especially useful solution to this. You can drop support for obsolete syntax and features once you release a new major version.

**Comment by horosgrisa** [comment]
@jjangga0214 Ok. I will release a stable release soon and will support stable zpm syntax. After that, I will make git tags.
