### ISSUE TITLE
Calling xargs with -P0 on mac fails

### ISSUE THREAD

**Issue by Salient** [zpm-zsh/zpm#12]
Line 180 in lib/functions.zsh: 
`xargs -0 -P0 -n1 "${_ZPM_DIR}/bin/_ZPM-plugin-helper" install`

results in 
> xargs: max. processes must be >0

on macOS, killing ZPM and leaves a bit of a mess. Some cached scripts get made, but the clean function doesn't get added.

changing -P0 to -P1 fixes the issue.

**Comment by horosgrisa** [comment]
@Salient I changed xargs params. run:
```sh
cd ~/.zpm
git pull
zpm clean
```
