### ISSUE TITLE
command not found: add-zsh-hook

### ISSUE THREAD

**Issue by lemons990** [zpm-zsh/zpm#13]
I added it to my .zshrc file and it gives me this error:

/var/folders/v2/wx3l7mt117q4jygt86g745t00000gp/T//.zpm-cache-JP.zsh:26: command not found: add-zsh-hook

I have oh-my-zsh installed as well as brew

**Comment by lemons990** [comment]
I should have mentioned I'm using iTerm, but in the default terminal application I get:

Usage: add-zsh-hook hook function
Valid hooks are:
  chpwd precmd preexec periodic zshaddhistory zshexit zsh_directory_name

**Comment by horosgrisa** [comment]
@lemons990 Hello. 
Can you show a part of `.zshrc` related to zpm?

**Comment by horosgrisa** [comment]
@lemons990 Check new commit, run `git pull` in `~/.zpm` folder, remove `/var/folders/v2/wx3l7mt117q4jygt86g745t00000gp/T//.zpm-cache-JP.zsh` and reopen terminal

**Comment by horosgrisa** [comment]
@lemons990 Hi, try to update the plugin now
