### ISSUE TITLE
Iterm session exiting when using cache

### ISSUE THREAD

**Issue by JoeWoodward** [zpm-zsh/zpm#14]
I've just installed zpm and had to debug this message
```
Usage: add-zsh-hook hook function
Valid hooks are:
  chpwd precmd preexec periodic zshaddhistory zshexit zsh_directory_name
```

I have found that if I delete the cache the terminal works correctly and doesn't exit. Any sessions after this one will show the error above and then exit. I think it might be something to do with autoloading add-zsh-config

**Comment by JoeWoodward** [comment]
In fact, maybe it's this line that is generated for the cached .zsh file
```
  add-zsh-hook -d background _ZPM_post_fn
```
background is not a valid hook

**Comment by JoeWoodward** [comment]
Couldn't a heredoc be used here to really cleanup that echo statement a lot too?

**Comment by JoeWoodward** [comment]
Ok, so background is added with the zpm-zsh/background plugin but doesn't seem to be loaded in a cached session

**Comment by horosgrisa** [comment]
@JoeWoodward Hi, I fixed it. try to update zpm from git

**Comment by JoeWoodward** [comment]
So fast! Thank you

**Comment by horosgrisa** [comment]
@JoeWoodward It works?

**Comment by JoeWoodward** [comment]
Yes, thank you
