### ISSUE TITLE
Does not work with zdharma/history-search-multi-word

### ISSUE THREAD

**Issue by lainiwa** [zpm-zsh/zpm#16]
I load the plugin as follows:
```sh
zpm load zdharma/history-search-multi-word
```
Ctrl+R issues the error:
```
_zsh_highlight_call_widget:3: history-search-multi-word: function definition file not found
```

However when I `source history-search-multi-word.plugin.zsh` manually it starts working just fine (`eval "$(<plugin)"`, as described in [the standard](https://github.com/zdharma/Zsh-100-Commits-Club/blob/master/Zsh-Plugin-Standard.adoc), works as well).

I've tried adding `,source:history-search-multi-word.plugin.zsh` with no effect.

What might be causing this?

**Comment by horosgrisa** [comment]
Of... This is described in README. it's normal behavour 

> add plugin folder to your $fpath, only if exist at least one _* file, enabled by default

This plugin doesn't contain any _* file, so it will not be added to $fpath,
You can manually add this plugin to fpath 

```sh
zpm load zdharma/history-search-multi-word,fpath:/
```

**Comment by horosgrisa** [comment]
@lainiwa Also, this plugin doesn't support [functions dir standard](https://github.com/zdharma/Zsh-100-Commits-Club/blob/master/Zsh-Plugin-Standard.adoc#funcs-dir)

**Comment by lainiwa** [comment]
Oh, indeed...
I expected .plugin.zsh to act the same way when sourced from within zpm and when manually sourced, which it seems not to be the case.

Thank you!

**Comment by horosgrisa** [comment]
@lainiwa Also, i made a pull request https://github.com/zdharma/history-search-multi-word/pull/23 for compatibility with zsh plugin standard
