### ISSUE TITLE
Support load plugin from command output, just like: kubectl

### ISSUE THREAD

**Issue by wweir** [zpm-zsh/zpm#17]
Some command-line tools contain its own completion script, just like: docker / kubectl / helm.
```
source <(kubectl completion zsh)
```
How about adding a new load type of loading from the command line output?
The async load logic should be useful to load such a big script of kubectl output.

**Comment by horosgrisa** [comment]
Hm...
Maybe I will do it in next way

```sh
zpm load cli/kubectl,type:cli,gen:"kubectl completion zsh",async
```
What do you feel about it?

**Comment by wweir** [comment]
That's cool!

**Comment by horosgrisa** [comment]
@wweir I'm not sure about `cli` prefix. Maybe you have a better option?

**Comment by wweir** [comment]
How about `cmd`?

**Comment by horosgrisa** [comment]
@wweir Now you can use following syntax:
```sh
zpm load cmd/kubectl,cmd:"kubectl completion zsh",async
# Or
zpm load kubectl,type:cmd,cmd:"kubectl completion zsh",async
```

**Comment by wweir** [comment]
It works correctly while configed as `zpm load cmd/kubectl,cmd:"kubectl completion zsh",async`.
But not work while configed as `zpm load kubectl,type:cmd,cmd:"kubectl completion zsh",async`.

**Comment by wweir** [comment]
Is it caused by no slash in the plugin name `kubectl`？

**Comment by wweir** [comment]
<img width="471" alt="图片" src="https://user-images.githubusercontent.com/2841254/79870328-63193f00-8415-11ea-8379-e16903c9ae0f.png">
The load time of async and sync loading. 
The completion script of kubectl is so huge.

**Comment by horosgrisa** [comment]
@wweir I changed the syntax 
```sh
zpm load kubectl,type:mkdir,gen-pl:"kubectl completion zsh",async
```
Or for completions
```sh
zpm load rustup,type:mkdir,gen-comp:"rustup completions zsh"
```

**Comment by horosgrisa** [comment]
@wweir I have a test script
Run:
```sh
./tests/startup/zsh
```

**Comment by wweir** [comment]
@horosgrisa On 6C12T 16G PCIE SSD rmbp.
``` shell
zsh -i -c exit  0.02s user 0.02s system 95% cpu 0.038 total
zsh -i -c exit  0.02s user 0.01s system 95% cpu 0.034 total
zsh -i -c exit  0.02s user 0.01s system 95% cpu 0.034 total
zsh -i -c exit  0.02s user 0.01s system 95% cpu 0.034 total
zsh -i -c exit  0.02s user 0.01s system 95% cpu 0.033 total
zsh -i -c exit  0.02s user 0.01s system 94% cpu 0.034 total
zsh -i -c exit  0.02s user 0.01s system 95% cpu 0.034 total
zsh -i -c exit  0.02s user 0.01s system 95% cpu 0.033 total
zsh -i -c exit  0.02s user 0.01s system 95% cpu 0.033 total
zsh -i -c exit  0.02s user 0.01s system 95% cpu 0.033 total
```

**Comment by horosgrisa** [comment]
Run `./tests/startup/zsh` in `~/.zpm` dir

**Comment by grigorii-horos** [comment]
@wweir See README
