### ISSUE TITLE
support download plugin from any git repository hosting service

### ISSUE THREAD

**Issue by wweir** [zpm-zsh/zpm#27]
I have used some plugin hosted by self-host git repository hosting service.

May I install plugin from that service?
Demand list：
1. download git repo from any git repository hosting service.
2. use the service as a mirror to speed up downloading.

**Comment by grigorii-horos** [comment]
I will add this possibility soon. Now you can use this as a temporary solution:
```
zpm load empty/my-plugin,hook:'git clone https://repo.com/ .'
```

**Comment by grigorii-horos** [comment]
@wweir Hello. I already did this, but only in next branch. 

```
zpm load git/plugin,origin:<some uul acceptable by git clone>
```

**Comment by wweir** [comment]
Thank you, it is quite useful for me.
The only issue is [`zpm-zsh/helpers` ](https://github.com/zpm-zsh/zpm/blob/205c1f267bc202b3f8ab91148f4259fa7c215c6d/lib/imperative.zsh#L8), but I have some tricks to bypass it.

**Comment by grigorii-horos** [comment]
Hey @wweir . What kind of issue?

**Comment by wweir** [comment]
`zpm-zsh/helpers` is auto load in src from github origin, the setting in the `.zshrc` file dose not work.

**Comment by wweir** [comment]
https://github.com/zpm-zsh/zpm/blob/205c1f267bc202b3f8ab91148f4259fa7c215c6d/lib/imperative.zsh#L8
