### ISSUE TITLE
How to chenge the default @omz link?

### ISSUE THREAD

**Issue by ysl2** [zpm-zsh/zpm#31]
Hi, I come from China, the original oh-my-zsh link address(`https://github.com/ohmyzsh/ohmyzsh`) is slow beacuse China's country network firewall.
So I was wondering if zpm cound change the default `@omz` address?
I always use `https://hub.fastgit.org/` to replace `https://github.com/`. `hub.fastgit.org` is a China mirror of github.

Thanks! :-)

**Comment by grigorii-horos** [comment]
Hello @ysl2 . Maybe I can help you in another way.

For example: I can add support for an env variable who will be used to replace `github.com` in all urls?

Like: 
```sh
export GITHUB_MIRROR='https://some.site.ch/'
zpm load some/plugin # Plugin will be loaded from https://some.site.ch/some/plugin, not from https://github.com/some/plugin
```

If this is a good solution, can you provide the best github mirror in China? Or `hub.fastgit.org` is the best?

**Comment by grigorii-horos** [comment]
@ysl2 Initial implementation done in `next` branch. See: https://github.com/zpm-zsh/zpm/tree/next#configuration

**Comment by ysl2** [comment]
> @ysl2 Initial implementation done in `next` branch. See: https://github.com/zpm-zsh/zpm/tree/next#configuration

Sorry for my late reply, here are some mirror format:

---

Original(https):

https://github.com/zpm-zsh/zpm.git

Substitute(https):

https://hub.fastgit.org/zpm-zsh/zpm.git 

https://ghproxy/https://github.com/zpm-zsh/zpm.git

---

Original(ssh):

git@github.com:zpm-zsh/zpm.git

Substitute(ssh):

git@git.zhlh6.com:zpm-zsh/zpm.git

---

Original(raw):

https://raw.githubusercontent.com/{user}/{repo}/{branch}/{file}

Substitute(raw):

https://cdn.jsdelivr.net/gh/{user}/{repo}/{file}

**Comment by ysl2** [comment]
And there are more mirrors in my personal note:

https://github.com/ysl2/my-notes/blob/master/linux/distribution/manjaro/04-github-download-mirror.md
