### ISSUE TITLE
zpm upgrade report xargs warning

### ISSUE THREAD

**Issue by wweir** [zpm-zsh/zpm#32]
**Describe the bug**

execuete `zpm upgrade`, then it report 
```sh
xargs: warning: options --max-args and --replace/-I/-i are mutually exclusive, ignoring previous --max-args value
```

**Screenshots**
![image](https://user-images.githubusercontent.com/2841254/124216059-ec52f800-db27-11eb-973b-a0c06231c275.png)

**Comment by grigorii-horos** [comment]
@wweir Done in `next` branch
