### ISSUE TITLE
Error on initial install

### ISSUE THREAD

**Issue by Onfroygmx** [zpm-zsh/zpm#33]
**Describe the bug**
Error after fresh install

**To Reproduce**
- Clean archlinux install.
- git clone --recursive https://github.com/zpm-zsh/zpm ~/.zpm
- echo "source ~/.zpm/zpm.zsh" > .zshrc
- restart shell:
- 
xargs: warning: options --max-args and --replace/-I/-i are mutually exclusive, ignoring previous --max-args value
Install zpm-zsh/helpers ✔

**Expected behavior**
no errors

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux arch 5.12.15-arch1-1 #1 SMP PREEMPT Wed, 07 Jul 2021 23:35:29 +0000 x86_64 GNU/Linu

**Smartphone (please complete the following information):**

**Additional context**
Just a fresh install

**Comment by grigorii-horos** [comment]
@Onfroygmx Don't worry! This is just warning that already fixed. Please update zpm using `zpm update`
