### ISSUE TITLE
zpm tries to source files in my current directory, instead of the plugin directory

### ISSUE THREAD

**Issue by sindre-nistad** [zpm-zsh/zpm#36]
**Describe the bug**
When starting a shell, I get an error message saying "Cannot source <current directory>/<plugin.zsh>"

**To Reproduce**
```bash
zpm load @omz
zpm load @omz/osx
```

**Expected behavior**
I expect the plugin to be loaded, and not exit the startup procedure.

**Additional context**

When I look at the source code of the affected plugins, it seems that `${0:A:h}`, which if often used to reference the directory of the file being sourced / executed, resolves to my current directory.

**Comment by grigorii-horos** [comment]
Hey @sindre-nistad I think I fixed this error in one of last commits. Can you check now?

**Comment by mcornella** [comment]
The `osx` plugin was renamed to `macos`, you should do
```sh
zpm load @omz
zpm load @omz/macos
```
This can be closed.
