### ISSUE TITLE
Can't upgrade @zpm

### ISSUE THREAD

**Issue by cyruseuros** [zpm-zsh/zpm#38]
**Describe the bug**
During every upgrade zpm reports: `Can't upgrade @zpm ✖`

**To Reproduce**
Bootstrap installation based on README installation:
```zsh
if [[ ! -f ~/.zpm/zpm.zsh ]]; then
  git clone --recursive https://github.com/zpm-zsh/zpm ~/.zpm
fi
source ~/.zpm/zpm.zsh
```
run `zpm u`

**Expected behavior**
Either `Upgrade @zpm ✔`, or `Skip upgrade @zpm ✔`

**Comment by wurosh** [comment]
Fixed, thanks! And thank you for the most straightforward package manager I've used thus far. The only thing that comes close in terms of performance is zinit, but it took me months to learn how to use it properly.
