### ISSUE TITLE
When terminal is opened for the first time it works, next time terminal is opened it doesn't work

### ISSUE THREAD

**Issue by young-druid** [zpm-zsh/zpm#39]
I have a quite simple config in .zshrc. When I open terminal for the first time it works. Next time I open it I get
```
Last login: Mon Nov  1 15:51:14 on ttys002
(anon):source:3: no such file or directory: /Users/myuser/zsh-history-substring-search.zsh
```

I am on macOS Big Sur 11.6. zsh version is 5.8. My config is quite simple at the moment
```
if [[ ! -f ~/.zpm/zpm.zsh ]]; then
  git clone --recursive https://github.com/zpm-zsh/zpm ~/.zpm
fi
source ~/.zpm/zpm.zsh
zpm load zsh-users/zsh-history-substring-search
```
When I run `rm -rf "${TMPDIR:-/tmp}/zsh-${UID:-user}"` and open terminal again it works fine but next time I open terminal it show me that error again.

**Comment by grigorii-horos** [comment]
Hey @young-druid . Phis plugin has a bug. It can't detect plugin folder.

[0=${(%):-%N}](https://github.com/zsh-users/zsh-history-substring-search/blob/master/zsh-history-substring-search.plugin.zsh#L1)


But you can bypass this

```sh
zpm load zsh-users/zsh-history-substring-search,source:zsh-history-substring-search.zsh
```

**Comment by young-druid** [comment]
I see now. I don't think this is a plugin bug. I noticed you said that there is a bug in another [plugin](https://github.com/zpm-zsh/zpm/issues/36). But it is a common way to define plugins nowadays. Many zsh plugin managers support this specification: [zcomet](https://github.com/agkozak/zcomet), [zgenom](https://github.com/jandamm/zgenom) and [zinit](https://github.com/zdharma-continuum/zinit). I am not insisting zpm supports it as well. But you may notice that quite a big amount of plugins use that notation: `0=${(%):-%N}`.
It was proposed as a standard [here](https://zdharma-continuum.github.io/zinit/wiki/zsh-plugin-standard/#1_standardized_0_handling). So if you can have a look and see if it is possible for zpm to support it that would be cool.

**Comment by young-druid** [comment]
For example there is another [one](https://github.com/woefe/git-prompt.zsh).

**Comment by grigorii-horos** [comment]
@young-druid zpm supports this standard. Also, I use this approach in my plugins. Take a look here: https://github.com/zpm-zsh/autoenv/blob/master/autoenv.plugin.zsh#L3

But this header with $0 handler missing in **zsh-users/zsh-history-substring-search**

**Comment by young-druid** [comment]
Yes. You are right. This header is missing in both plugins.
