### ISSUE TITLE
Cannot make gen-completion to work

### ISSUE THREAD

**Issue by young-druid** [zpm-zsh/zpm#40]
I have the following line `zpm load @empty/kubectl,gen-completion:"kubectl completion zsh"`. With debug enabled I see
```
zpm:init Initialize '@empty/kubectl'
zpm:init:fpath Add to $fpath '/Users/myuser/.zpm/plugins/@empty---kubectl/functions'
zpm:init:source Plugin file for @empty/kubectl is missing
```
File `/Users/myuser/.zpm/plugins/@empty---kubectl/functions/_kubectl` is empty. My impression that it should contain the output of `kubectl completion zsh`. Thus kubectl completion doesn't work. Am I doing something wrong?

Also, README says to use `zpm @empty/rustup,gen-completion:"rustup completions zsh"` but zpm will show a warning that `load` is missing so it looks more correct version is `zpm load @empty/rustup,gen-completion:"rustup completions zsh"`, right?

**Comment by grigorii-horos** [comment]
Hm... Very strange. I tried to copy your snippet to my .zshrc, but it works without any problem. 

Can you execute ?

```sh
zpm u @empty/kubectl
```

Also, check if `kubectl completion zsh` generate correct code

**Comment by young-druid** [comment]
After I ran this command `zpm u @empty/kubectl` it works. I started from scratch and it works now fine. Not sure why it didn't work from the beginning. Now I cannot reproduce it even after wiping everything zpm-related out.

**Comment by grigorii-horos** [comment]
I think that the generation was broken at the first execution, and this result was cached.

**Comment by young-druid** [comment]
Yes. When I ran it for the first time I made a typo. And where is cache located?

**Comment by grigorii-horos** [comment]
Cache located here: `/tmp/zsh-$UID`
But you can clean using `zpm clean`
