### ISSUE TITLE
command not found: check-if

### ISSUE THREAD

**Issue by kghost** [zpm-zsh/zpm#41]
After a fresh install w/o any configuration, using provided `zshrc` as default zshrc

```
zpm:10: command not found: check-if
zpm:10: command not found: check-if
zpm:10: command not found: check-if
zpm:18: command not found: check-if
zpm:10: command not found: check-if
zpm:18: command not found: check-if
```

I'm unable to find what's `check-if`, did you define this function somewhere else ?

**Comment by grigorii-horos** [comment]
Hey @kghost . This function declared in another plugin [helpers](https://github.com/zpm-zsh/helpers). But this plugin should be installed by zpm by default. 

Can you clean your zsh cache? 

```sh
rm -rf /tmp/zsh-*
```

**Comment by kghost** [comment]
I have tried it several times, removing the cache doesn't help, can you show me where is the 'check-if' function define ? So I can help diagnosis the problem.

**Comment by grigorii-horos** [comment]
Hm....

Maybe you need to clean cache and all installed plugins

```sh
rm -rf /tmp/zsh-*
rm -rf ~/.zpm/plugins/*
```

**Comment by kghost** [comment]
Added `set -x` at the beginning of `.zshrc`. this is the result:

```
+/home/.zpm/zpm.zsh:30> eval $'#!/usr/bin/env zsh\n\nmkdir -p "${ZSH_CACHE_DIR}" "${ZSH_CACHE_DIR}/functions" "${ZSH_CACHE_DIR}/bin"\n\ncompinit -i -C -d "${_ZPM_COMPDUMP}"\n\ndeclare -Ag _ZPM_plugins_full=( \'@zpm\' \'@zpm\' )\n@zpm-load-plugins zpm-zsh/helpers\n\nsched +1 @zpm-background-initialization\n\nfunction source() {\n  if [[ ! "${1}.zwc" -nt "${1}" ]]; then\n    zcompile "${1}" 2>/dev/null\n  fi\n\n  builtin source "$1"\n}'
+(eval):3> mkdir -p /tmp/zsh-724065 /tmp/zsh-724065/functions /tmp/zsh-724065/bin
+(eval):5> compinit -i -C -d /tmp/zsh-724065/zcompdump
+/home/.zshrc:11> zpm if openwrt load zpm-zsh/openwrt
```

It looks like that `lib/imperative.zsh` is not loaded completely, the execution terminated after line 5

**Comment by kghost** [comment]
With `DEBUG=zpm`

```
% zsh
zpm:init Initialize 'zpm-zsh/helpers'
zpm:init:source Plugin file for zpm-zsh/helpers is missing
zpm:10: command not found: check-if
zpm:10: command not found: check-if
zpm:10: command not found: check-if
zpm:18: command not found: check-if
zpm:init Initialize 'zpm-zsh/tmux'
zpm:init:source Sourcing for zpm-zsh/tmux is disabled
```

**Comment by kghost** [comment]
I have found the problem, I'm using `parallel` from `moreutils` (https://joeyh.name/code/moreutils/, https://packages.debian.org/sid/moreutils)

Which doesn't compatible with GNU parallel, so `functions/@zpm-launch-plugin-helper` doesn't work at all

**Comment by grigorii-horos** [comment]
@kghost Wow... Can you help me with detection of this `paralllel`? Can you send me `paralllel --help` output?

**Comment by kghost** [comment]
```
 $ parallel.moreutils -h
parallel [OPTIONS] command -- arguments
	for each argument, run command with argument, in parallel
parallel [OPTIONS] -- commands
	run specified commands in parallel
```

**Comment by grigorii-horos** [comment]
@kghost Hello. 

Now you can use `_ZPM_PARALLEL_RUNNER` to change parallel program. In your case this can be like:
```sh
_ZPM_PARALLEL_RUNNER=xargs

...

source zpm.zsh
```
