### ISSUE TITLE
Unable to load zsh-history-substring-search

### ISSUE THREAD

**Issue by tkolleh** [zpm-zsh/zpm#42]
How to load `zsh-history-substring-search`? 

Trying to understand why `zsh-history-substring-search` is not loading. Is there a [custom implementation](https://github.com/zpm-zsh/zpm/blob/5d5cb0e320b4c1a5207ac61713715344d7244bf2/zshrc#L45) that you're testing against (using).

**Remove comment [see full file](https://github.com/tkolleh/dotfiles/blob/master/dot_zshrc):**

```
  94   │ #zpm load @github/zsh-users/zsh-syntax-highlighting
  95   │ #zpm load @github/zsh-users/zsh-completions
  96   │ zpm load @github/zsh-users/zsh-history-substring-search
  97   │ #zpm load @github/zsh-users/zsh-autosuggestions
```

**Get error:**

```
(anon):source:3: no such file or directory: /Users/tkolleh/zsh-history-substring-search.zsh
```

<details>

- OS: macOS 12.0.1 21A559 arm64
- Host: MacBookPro18,3
- Shell: zsh 5.8
- Terminal: iTerm2
- CPU: Apple M1 Pro

</details>

**Comment by grigorii-horos** [comment]
Hey @tkolleh . `zsh-history-substring-search` plugin incorrectly detect $0 variable, you can use this hook
```sh
zpm load @github/zsh-users/zsh-history-substring-search,source:zsh-history-substring-search.zsh
```

But will be better to use my fork of this plugin, with optimizations and without this problem
```sh
zpm load zpm-zsh/zsh-history-substring-search,async
```

**Comment by tkolleh** [comment]
Thanks that resolved my issue.
