### ISSUE TITLE
autoload theme doesn't work

### ISSUE THREAD

**Issue by zfben** [zpm-zsh/zpm#43]
**Describe the bug**

I want to load a theme when opening a new terminal, is `autoload` do that?

**To Reproduce**

I have tried `zpm load romkatv/powerlevel10k,autoload` and `zpm load @theme/romkatv/powerlevel10k,autoload`

They just work in the current shell.

**Expected behavior**

Autoload without inputting commands.

**Additional context**

**Comment by grigorii-horos** [comment]
Hey @zfben. 
* Autoload works with autoloadable functions in next way `autoload=function1,function2`, not just `autoload`. Maybe do you mean `async`? This theme doesn't provide something like this, so you can remove autoload tag
* Are you saved this in your `.zshrc`?

**Comment by zfben** [comment]
@grigorii-horos I tried to run `zpm load romkatv/powerlevel10k,async`, it only works on the current shell.
Then I tried to add this command to .zshrc, it showed the theme in a second and then restored to default.

I want to set powerlevel10k as zsh's default theme.

**Comment by grigorii-horos** [comment]
I think you should load this theme in sync mode

Add this into your `.zshrc` 
```
zpm load romkatv/powerlevel10k
```

**Comment by zfben** [comment]
> I think you should load this theme in sync mode
> 
> Add this into your `.zshrc`
> 
> ```
> zpm load romkatv/powerlevel10k
> ```

@grigorii-horos I tied it, but it now works :(

The .zshrc content is:

```zsh
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

if [[ ! -f ~/.zpm/zpm.zsh ]]; then
  git clone --recursive https://github.com/zpm-zsh/zpm ~/.zpm
fi
source ~/.zpm/zpm.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export NVM_DIR="$HOME/.nvm"
  [ -s "/usr/local/opt/nvm/nvm.sh" ] && \. "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

zpm load romkatv/powerlevel10k
```

Is it something wrong?

**Comment by grigorii-horos** [comment]
Hey @zfben . I found a bug in `romkatv/powerlevel10k`. You can use my temporary fork of this repo: `zpm-zsh/powerlevel10k`

**Comment by zfben** [comment]
It dosen't work.

My steps are:

1. run `zpm load zpm-zsh/powerlevel10k`
2. write the command to .zshrc

Now my .zshrc is:

```zsh
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
# if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
#  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
# fi

if [[ ! -f ~/.zpm/zpm.zsh ]]; then
  git clone --recursive https://github.com/zpm-zsh/zpm ~/.zpm
fi
source ~/.zpm/zpm.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export NVM_DIR="$HOME/.nvm"
  [ -s "/usr/local/opt/nvm/nvm.sh" ] && \. "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

zpm load zpm-zsh/powerlevel10k
```

**Comment by grigorii-horos** [comment]
@zfben What error do you have? I tried your zshrc and it's works
https://asciinema.org/a/a2Q5Ku0ztNGLgYSmlEqorXM0R

**Comment by zfben** [comment]
@grigorii-horos i forgot to run zpm clean. it works now, thank you.

**Comment by zfben** [comment]
@grigorii-horos by the way, could you create a pull request to powerlevel10k? then I can use the official powerlevel10k source.

**Comment by grigorii-horos** [comment]
Hey @zfben I tied, but author doesn't want to accept pr

https://github.com/romkatv/powerlevel10k/pull/1678

You can add a comment here,  I think

**Comment by zfben** [comment]
Hmm, I don't good at zsh, I guess the author thinks the source changes maybe make it more complex or bugs.

**Comment by grigorii-horos** [comment]
Hey @zfben . I did another fix for this issue. Now `zpm load romkatv/powerlevel10k` should work fine. Try to run 
```sh
zpm update
```

**Comment by zfben** [comment]
When i ran `zpm update`, it shows `Unknown command `zpm update`, treat as `zpm load update`
Skip install update ✖`

Then I goto ~/.zpm and git pull directly.

After I run `zpm load romkatv/powerlevel10k` and `zpm clean`, then I open a new shell, it shows `no such file or directory: /private/var/folders/r9/4jr03m4169xfqm2sgg7j_dd40000gn/T/zsh-501/internal/p10k.zsh`.

Now the .zshrc is:
```zsh
if [[ ! -f ~/.zpm/zpm.zsh ]]; then
  git clone --recursive https://github.com/zpm-zsh/zpm ~/.zpm
fi
source ~/.zpm/zpm.zsh

export NVM_DIR="$HOME/.nvm"
  [ -s "/usr/local/opt/nvm/nvm.sh" ] && \. "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

zpm load romkatv/powerlevel10k
#source ~/powerlevel10k/powerlevel10k.zsh-theme
zpm load zfben/zsh-npm
```

**Comment by grigorii-horos** [comment]
@zfben Sorry... Use `zpm upgrade`. I forgotten own function name 😹

**Comment by zfben** [comment]
After i run `zpm upgrade`, it shows same error in new terminal.

**Comment by jqhr** [comment]
@grigorii-horos 
I delete /tmp/zsh-1000/zpm-cache.zsh, it works

**Comment by dakky** [comment]
so basically this issue still exists. Are there any plans to fix that?

**Comment by grigorii-horos** [comment]
@dakky @zfben Please add this before powerlevel10k init

```sh
export POWERLEVEL9K_INSTALLATION_DIR=~/.zpm/plugins/romkatv---powerlevel10k

# powerlevel10k init
zpm load romkatv/powerlevel10k

```
