### ISSUE TITLE
(anon):source:27: no such file or directory: /tmp/zsh-1000/internal/p10k.zsh

### ISSUE THREAD

**Issue by xfzv** [zpm-zsh/zpm#48]
**To Reproduce**

Minimal `.zshrc`:

```zsh
if [[ ! -f ~/.zpm/zpm.zsh ]]; then
  git clone --recursive https://github.com/zpm-zsh/zpm ~/.zpm
fi
source ~/.zpm/zpm.zsh

zpm load romkatv/powerlevel10k
```

1. Quit immediately the initial `powerlevel10k` setup (doesn't matter, the issue occurs even if we complete it)
2. The prompt is correctly loaded
3. Run `exec zsh` or run a new terminal instance
4. The following error keeps appearing every time a new shell is spawned:

```zsh
(anon):source:27: no such file or directory: /tmp/zsh-1000/internal/p10k.zsh
```

**Expected behavior**

The plug-in should load normally without any error.

**Additional context**

[This workaround](https://github.com/zpm-zsh/zpm/issues/46#issuecomment-1058697861) works provided I add the command to my `.zshrc` file (before sourcing `zpm`) so that it's run every time. Otherwise, it works only once (until the directory is created again).

No issue whatsoever with other Zsh plugins managers.

**Comment by grigorii-horos** [comment]
@kisaragi-hiu Fixed in main. This workaround will be used automatically
