### ISSUE TITLE
It doesn't work until upgrade

### ISSUE THREAD

**Issue by jvzaniolo** [zpm-zsh/zpm#50]
**Describe the bug**
The shell continues being the default zsh shell after installing everything

**To Reproduce**

`zpm clean; rm -rf zpm`

```bash
#!/usr/bin/env zsh

source ~/.zpm/zpm.zsh 2>/dev/null || {
  git clone https://github.com/zpm-zsh/zpm ~/.zpm
  source ~/.zpm/zpm.zsh
}

zpm load zpm-zsh/minimal-theme

zpm if-not ssh load                                   \
  zpm-zsh/zsh-autosuggestions,async                   \
  zpm-zsh/fast-syntax-highlighting,async              \
  zpm-zsh/nvm

source ~/.zshrc.local 2>/dev/null
``` 

**Expected behavior**
When opening a new Terminal window (Windows Terminal + WSL in my case) it should show the minimal theme with zsh-autosuggestions and syntax highlighting but that doesn't work until you run `zpm upgrade`

**Additional context**

**Comment by grigorii-horos** [comment]
Fixed in main
