### ISSUE TITLE
Why do we need to source ~/.zshrc.local if the file doesn't exist?

### ISSUE THREAD

**Issue by jvzaniolo** [zpm-zsh/zpm#51]
**Describe the bug**

This is a question regarding the `source ~/.zshrc.local > 2>/dev/null` line in the `zshrc` README example.

**Comment by grigorii-horos** [comment]
This is just an example. You can remove this line without if you want.

P.S. This `zshrc` is my real config, but some private code I can't upload to GitHub, so I keep it in `~/.zshrc.local`
