### ISSUE TITLE
macOS installation error

### ISSUE THREAD

**Issue by jvzaniolo** [zpm-zsh/zpm#52]
**Describe the bug**

Error after installing zpm to macOS `.zshrc`

 ```bash
$ 
(anon):26: redirection with no command
(anon):24: no matches found: /Users/joao.zaniolo/.zpm/plugins/zpm-zsh---material-colors/dircolors/*.dircolors
 $ 
[3]    exit 1     for file in "${_DIRNAME}/dircolors/"*.dircolors; do; cat "$file"; done
 $ 
```

![CleanShot 2022-03-25 at 1 11 46@2x](https://user-images.githubusercontent.com/54036572/160052836-6c857802-c145-41a3-a19f-e0c83beb1d5c.png)

**To Reproduce**

Add the following to `~/.zshrc`

```bash
#!/usr/bin/env zsh

source ~/.zpm/zpm.zsh 2>/dev/null || {
  git clone https://github.com/zpm-zsh/zpm ~/.zpm
  source ~/.zpm/zpm.zsh
}

zpm load zpm-zsh/minimal-theme

zpm if-not ssh load                                   \
  zpm-zsh/zsh-autosuggestions,async                   \
  zpm-zsh/fast-syntax-highlighting,async              \
  zpm-zsh/nvm,async

source ~/.zshrc.local 2>/dev/null
```

**Expected behavior**

Everything working fine

**Additional context**

**Comment by grigorii-horos** [comment]
@jvzaniolo This error isn't related to zpm, it happened in another plugin. 

But this plugin also created by me.
So, show the output of this
```sh
ls /Users/joao.zaniolo/.zpm/plugins/zpm-zsh---material-colors/dircolors/*.dircolors
```

**Comment by grigorii-horos** [comment]
Or just disable this plugin...

**Comment by jvzaniolo** [comment]
Gotcha, this is the output of the command:

```bash
$ ls /Users/joao.zaniolo/.zpm/plugins/zpm-zsh---material-colors/dircolors/*.dircolors

/Users/joao.zaniolo/.zpm/plugins/zpm-zsh---material-colors/dircolors/50-linux-desktop.dircolors
/Users/joao.zaniolo/.zpm/plugins/zpm-zsh---material-colors/dircolors/50-linux.dircolors
/Users/joao.zaniolo/.zpm/plugins/zpm-zsh---material-colors/dircolors/50-rc.dircolors
/Users/joao.zaniolo/.zpm/plugins/zpm-zsh---material-colors/dircolors/50-ssh.dircolors
/Users/joao.zaniolo/.zpm/plugins/zpm-zsh---material-colors/dircolors/50-sublime-text.dircolors
/Users/joao.zaniolo/.zpm/plugins/zpm-zsh---material-colors/dircolors/50-systemd.dircolors
/Users/joao.zaniolo/.zpm/plugins/zpm-zsh---material-colors/dircolors/50-vscode.dircolor
```

**Comment by jvzaniolo** [comment]
And I think that because of that error, the `zpm` command or any other command I installed via `zpm load` is not recognized

**Comment by jvzaniolo** [comment]
> Or just disable this plugin...

@grigorii-horos How can I do that?

**Comment by grigorii-horos** [comment]
@jvzaniolo I don't know why this happened. Can you disable this plugin temporally?

**Comment by jvzaniolo** [comment]
@grigorii-horos How can I disable the plugin? I think it’s a dependency of the minimal theme I’m using

**Comment by jvzaniolo** [comment]
I could just use another theme but I really liked the minimal theme 😕

**Comment by grigorii-horos** [comment]
@jvzaniolo Hey. Do you have GNU coreutils? I installed FreeBSD to check this bug, and now I know the problem. This plugin tries to run dircolors, but it's missing
