### ISSUE TITLE
Support for custom commands when loading

### ISSUE THREAD

**Issue by KyleUltimate** [zpm-zsh/zpm#54]
**Is your feature request related to a problem? Please describe.**
starship doesn't work without this `'eval "$(starship init zsh)"'`

**Describe the solution you'd like**

add a tag smth like `blah/blah,cmd:'eval "$(starship init zsh)"'`

**Describe alternatives you've considered**
obviously using other prompts
**Additional context**
There might currently be a way to do this, but I just can't find it

**Comment by grigorii-horos** [comment]
Hey @KyleUltimate 
Just add this to your `.zshrc`

```sh
zpm load @exec/starship,origin:'starship init zsh'
```

**Comment by KyleUltimate** [comment]
Huh, that's an interesting way to use origin. Thanks!
