### ISSUE TITLE
Cant Upgrade error for a lot of packages

### ISSUE THREAD

**Issue by jparsert** [zpm-zsh/zpm#56]
I installed zpm today and tried to import a lot of packages that I had from zgen (used previously). I appended the zshrc lines to this post. I run `zpm clean` after that I run `zpm upgrade`. Then the following happens:

- I get a "Can't upgrade X " where X is @github/ael/code/zsh ...., zsh256color, zsh-syntax-highliting and zsh-autosuggestions
- The upgrade process seems to be stuck after history-search-multi-word and can only be stopped with Ctrl+C.

relevant zshrc:

```
if [[ ! -f ~/.zpm/zpm.zsh ]]; then
  git clone --recursive https://github.com/zpm-zsh/zpm ~/.zpm
fi
source ~/.zpm/zpm.zsh

zpm load @omz

zpm load                \
  @omz/lib/compfix      \
  @omz/lib/completion   \
  @omz/lib/directories  \
  @omz/lib/functions    \
  @omz/lib/git          \
  @omz/lib/grep         \
  @omz/lib/history      \
  @omz/lib/key-bindings \
  @omz/lib/misc         \
  @omz/lib/spectrum     \
  @omz/lib/theme-and-appearance

zpm load @omz/git
zpm load @omz/archlinux
zpm load @omz/theme/norm
zpm load @omz/mercurial

zpm load zpm-zsh/ls
zpm load @github/zsh-users/zsh-syntax-highlighting
#zpm load chrissicool/zsh-256color

#zpm load @github/chrissicool/zsh-256color
#zpm load MikeDacre/careful_rm
#zpm load @github/zsh-users/zsh-autosuggestions
zpm load @github/changyuheng/fz
#zpm load @github/ael-code/zsh-colored-man-pages
zpm load @github/zdharma-continuum/history-search-multi-word
```

**Comment by grigorii-horos** [comment]
@jparsert Very strange, because I can upgrade everything.

Maybe this happens due to some dirty files in these repos. Pleae run
```sh
rm -rf ~/.zpm/plugins*
zpm clean
```
 
![image](https://user-images.githubusercontent.com/4980269/207319267-ddf8aeb9-856d-48cf-b4b8-84503c95777b.png)
