### ISSUE TITLE
Bookmarks plugin doesnt work

### ISSUE THREAD

**Issue by Amparose** [zpm-zsh/zpm#57]
**Describe the bug**
Bookmarks plugin doesnt work on M1 MacOS Ventura 13.1.

**To Reproduce**
Fresh install and added this to .zshrc:

```shell
if [[ ! -f ~/.zpm/zpm.zsh ]]; then
  git clone --recursive https://github.com/zpm-zsh/zpm ~/.zpm
fi
source ~/.zpm/zpm.zsh

zpm load "zpm-zsh/zshmarks"
```

After reloading terminal and confirming zpm is installed and working by typing `zpm`, none of the Bookmark commands work like `c`, `mark`, etc. The directory `.zpm/plugins/zpm-zsh---zshmarks` exists.

**Comment by grigorii-horos** [comment]
@Amparose Hey. Please use the new plugin name `zpm-zsh/bookmarks`, so use `zpm load zpm-zsh/bookmarks`

**Comment by Amparose** [comment]
Great that worked. Should probably [update documentation](https://github.com/zpm-zsh/bookmarks#zpm).
